CREATE DATABASE AAMG20230821;
GO

USE AAMG20230821;
GO

CREATE TABLE Libros (
    Id INT PRIMARY KEY IDENTITY(1,1),
    titulo NVARCHAR(255) NOT NULL,
    autor NVARCHAR(255) NOT NULL,
    año_publicación INT NOT NULL
);

select * from Libros

